export enum KoinlyLabel {
    AIRDROP = "airdrop",
    FORK = "fork",
    MINING = "mining",
    STAKING = "staking",
    LOAN_INTEREST = "loan_interest",
    OTHER_INCOME = "other_income",
    GIFT = "gift",
    LOST = "lost",
    COST = "cost",
    MARGIN_INTEREST_FEE = "margin_interest_fee",
    MARGIN_TRADE_FEE = "margin_trade_fee",
    REALIZED_GAIN = "realized_gain",
    SWAP = "swap",
    LIQUIDITY_IN = "liquidity_in",
    LIQUIDITY_OUT = "liquidity_out",
    NO_LABEL = "no_label",
    FROM_POOL = "from_pool",
    TO_POOL = "to_pool",
}